UPDATE UW_PROCESS 
SET STATUS_CD = 'WITHDRAWN' 
WHERE SUBJECT_REF_ID = 'valor1';
UPDATE UW_PROCESS 
SET STATUS_CD = 'WITHDRAWN' 
WHERE SUBJECT_REF_ID = 'valor2';
UPDATE UW_PROCESS 
SET STATUS_CD = 'WITHDRAWN' 
WHERE SUBJECT_REF_ID = 'valor3';
UPDATE UW_PROCESS 
SET STATUS_CD = 'WITHDRAWN' 
WHERE SUBJECT_REF_ID = 'valor4';
